# Matrix operations

In [1]:
import numpy as np
%run ~/.jupyter/config.ipy

# Matmul

In [8]:
A = np.array([
    [1, 2],
    [3, 4],
])

print("Normal matrix multiplication Ax where x is a column vector. Results in a column vector.")
print(np.matmul(A, np.array([[1], [2]])))

print("\nFor Ax, if x is 1d it is promoted to a matrix by appending 1 to its dimensions (makes it a column vector). This extra dimension is then removed")
print(np.matmul(A, np.array([1, 2])))

Normal matrix multiplication Ax where x is a column vector. Results in a column vector.
[[ 5]
 [11]]

For Ax, if x is 1d it is promoted to a matrix by appending 1 to its dimensions (makes it a column vector). This extra dimension is then removed
[ 5 11]


In [14]:
print("Left matrix multiplication xA where x is a row vector. x is promoted to a vector by prepending 1 to its dimensions. This is removed and so results in a row vector.")
print(np.matmul(np.array([1, 2]), A))

print("\nLeft matrix multiplication xA where x is a 2d row matrx.")
print(np.matmul(np.array([[1, 2]]), A))

Left matrix multiplication xA where x is a row vector. x is promoted to a vector by prepending 1 to its dimensions. This is removed and so results in a row vector.
[ 7 10]

Left matrix multiplication xA where x is a 2d row matrx.
[[ 7 10]]


In [24]:
print("When doing a full x^T A x we can either:")

print("\nRely on promotion both times")
print(np.matmul(np.array([1, 2]), np.matmul(A, np.array([1, 2]))))

print("\nRely on promotion neither time and flatten")
print(np.matmul(np.array([[1, 2]]), np.matmul(A, np.array([[1], [2]]))).flatten())

When doing a full x^T A x we can either:

Rely on promotion both times
27

Rely on promotion neither time and flatten
[27]


In [46]:
print("To multiple Ax for many x, pass an array of shape (n, dims, 1)")
xr = np.array([[[1], [2]], [[1], [2]], [[1], [2]]])
print(xr.shape)
print(np.matmul(A, xr))

print("\nAnd similar for xA, shape is (n, 1, dims)")
xl = np.array([[[1, 2]], [[1, 2]], [[1, 2]]])
print(xl.shape)
print(np.matmul(xl, A))

print("\nAnd for x^T A x just do two matmul and flatten")
np.matmul(xl, np.matmul(A, xr)).flatten()

To multiple Ax for many x, pass an array of shape (n, dims, 1)
(3, 2, 1)
[[[ 5]
  [11]]

 [[ 5]
  [11]]

 [[ 5]
  [11]]]

And similar for xA, shape is (n, 1, dims)
(3, 1, 2)
[[[ 7 10]]

 [[ 7 10]]

 [[ 7 10]]]

And for x^T A x just do two matmul and flatten


array([27, 27, 27])

In [51]:
print("For x^T A x you usually just have one x in column vector (n, dims, 1) form. Tranpose with:")
xl = xr.transpose((0, 2, 1))
print(xl.shape, xr.shape)

For x^T A x you usually just have one x in column vector (n, dims, 1) form. Tranpose with:
(3, 1, 2) (3, 2, 1)
